server {
    listen 80;
    server_name introduction.local;
    location / {
        proxy_pass http://introduction:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name histology.local;
    location / {
        proxy_pass http://histology:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name skull.local;
    location / {
        proxy_pass http://skull:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name trunkarm.local;
    location / {
        proxy_pass http://trunkarm:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name legjoints.local;
    location / {
        proxy_pass http://legjoints:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name headnecktrunk.local;
    location / {
        proxy_pass http://headnecktrunk:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name armmuscles.local;
    location / {
        proxy_pass http://armmuscles:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name legmuscles.local;
    location / {
        proxy_pass http://legmuscles:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name nervoussystem.local;
    location / {
        proxy_pass http://nervoussystem:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name specialsenses.local;
    location / {
        proxy_pass http://specialsenses:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name flashcards1.local;
    location / {
        proxy_pass http://flashcards1:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name flashcards2.local;
    location / {
        proxy_pass http://flashcards2:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name flashcards3.local;
    location / {
        proxy_pass http://flashcards3:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name flashcardsfinal.local;
    location / {
        proxy_pass http://flashcardsfinal:80;
        proxy_set_header Host $host;
    }
}